### ISSUE TITLE
Tag the User in the birthday wish

### ISSUE THREAD

**Issue by sahil-s-246** [acesdit/Birthday-Bot#1]
The bot is wishing people without tagging them at the moment

**#todo** : Include ```<@{user_id}>``` in ```client_postMessage()```

**Comment by Rahul-2006** [comment]
Hi @sahil-s-246 
It looks like a small change can i try it?

**Comment by sahil-s-246** [comment]
Sure, go ahead
You can also improve the Gemini prompt if you'd like to

**Comment by Rahul-2006** [comment]
Can you please check it and let me know if you need any changes
Also can you elaborate the gemini prompt issue

**Comment by misha-khar** [comment]
might also give this a try if y'all dont mind

**Comment by misha-khar** [comment]
> Can you please check it and let me know if you need any changes Also can you elaborate the gemini prompt issue

Where are you retrieving the user_id variable? You would likely need to loop through the names to add them all to the message, also since the prompt seems to be for everyone with a birthday on that day, not one prompt per person. For example, if its just John's birthday that might work fine but if its John and Jane's birthday the Gemini prompt would return one message for both and you'd need to @ both of them in the appended part.

**Comment by sahil-s-246** [comment]
> Can you please check it and let me know if you need any changes Also can you elaborate the gemini prompt issue

@Rahul-2006 I apologize for not clarifying **user id** . Included a get_id() method to get ids for a given name

[https://api.slack.com/methods/users.list/code](https://api.slack.com/methods/users.list/code)

We can access the user ids of people who have their birthdays with this method by wrapping the id from the response in ```<@{id}>```
[https://api.slack.com/reference/surfaces/formatting#mentioning-users](https://api.slack.com/reference/surfaces/formatting#mentioning-users)
```python3
# Sample Response
{
    "ok": true,
    "user": {
        "name": "Sonny Whether",
        "id": "U0G9QF9C6"
    },
    "team": {
        "id": "T0G9PQBBK"
    }
}
```
For <@U0G9QF9C6> slack references @ Sonny Whether
So we wanted to include this id in the text of the message, 
But at the moment that text is Gemini's response, so we can add it in the prompt as well

**Comment by sahil-s-246** [comment]
> Where are you retrieving the user_id variable? You would likely need to loop through the names to add them all to the message, also since the prompt seems to be for everyone with a birthday on that day, not one prompt per person. For example, if its just John's birthday that might work fine but if its John and Jane's birthday the Gemini prompt would return one message for both and you'd need to @ both of them in the appended part.

Thank you for pointing it out and sure, you can give this a try as well

Included a get_id method that takes the name as the argument
So we'll have to call this method for every name in the list and we could supply the ids in Gemini's prompt or add it directly after prompt response

This is how the bot is currently sending birthday wishes

![Screenshot 2024-09-17 121112](https://github.com/user-attachments/assets/f4d0e723-7d5d-431e-8fd9-2d7f5ef7bddf)
